In [7]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, roc_auc_score

import mlflow
import mlflow.sklearn

In [8]:
df = pd.read_csv('dataset/airline_ticket_prices_dataset.csv')

In [9]:
df.head(2)

,Ticket_ID,Airline,Origin,Destination,Distance_km,Class,Days_Before_Departure,Price_USD
0,1,Saudia,Mumbai,Paris,2643,Economy,28,555.30
1,2,Etihad,Istanbul,Jeddah,8266,Business,98,2070.27

In [10]:
#first permorfing some information extraction

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Ticket_ID              250 non-null    int64
 1   Airline                250 non-null    object
 2   Origin                 250 non-null    object
 3   Destination            250 non-null    object
 4   Distance_km            250 non-null    int64
 5   Class                  250 non-null    object
 6   Days_Before_Departure  250 non-null    int64
 7   Price_USD              250 non-null    float64
dtypes: float64(1), int64(3), object(4)
memory usage: 15.8+ KB

In [11]:
#checking null values
df.isnull().sum()

Ticket_ID                0
Airline                  0
Origin                   0
Destination              0
Distance_km              0
Class                    0
Days_Before_Departure    0
Price_USD                0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.Airline.value_counts()

Airline
British Airways     36
Qatar Airways       36
Lufthansa           34
Saudia              32
Emirates            32
Turkish Airlines    30
Flynas              26
Etihad              24
Name: count, dtype: int64

In [14]:
df.Origin.value_counts()

Origin
Paris       32
Istanbul    31
Doha        28
London      27
Mumbai      26
Riyadh      23
Jeddah      22
New York    21
Cairo       21
Dubai       19
Name: count, dtype: int64

In [ ]:
## Preprocessing

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Airline'] = le.fit_transform(df['Airline'])
df['Origin'] = le.fit_transform(df['Origin'])

In [16]:
df

,Ticket_ID,Airline,Origin,Destination,Distance_km,Class,Days_Before_Departure,Price_USD
0,1,6,6,Paris,2643,Economy,28,555.30
1,2,2,3,Jeddah,8266,Business,98,2070.27
2,3,0,2,Riyadh,2698,First,21,1883.11
3,4,1,5,Istanbul,7956,First,24,5349.65
4,5,5,1,Dubai,1308,Business,60,516.19
...,...,...,...,...,...,...,...,...
245,246,5,0,Paris,2389,First,33,1513.01
246,247,7,2,Paris,6941,First,36,4298.76
247,248,6,1,London,7396,Business,34,3008.26
248,249,4,9,Istanbul,8028,Business,58,2540.92
249,250,1,8,New York,11507,Economy,72,1525.20

In [17]:
df['Destination'].value_counts()

Destination
Cairo       36
Riyadh      32
Istanbul    30
Paris       29
New York    24
Dubai       24
London      20
Doha        19
Mumbai      19
Jeddah      17
Name: count, dtype: int64

In [18]:
df['Destination'] = le.fit_transform(df['Destination'])

In [19]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['Economy', 'Business', 'First']])
df['Class'] = oe.fit_transform(df[['Class']])

In [20]:
df

,Ticket_ID,Airline,Origin,Destination,Distance_km,Class,Days_Before_Departure,Price_USD
0,1,6,6,8,2643,0.0,28,555.30
1,2,2,3,4,8266,1.0,98,2070.27
2,3,0,2,9,2698,2.0,21,1883.11
3,4,1,5,3,7956,2.0,24,5349.65
4,5,5,1,2,1308,1.0,60,516.19
...,...,...,...,...,...,...,...,...
245,246,5,0,8,2389,2.0,33,1513.01
246,247,7,2,8,6941,2.0,36,4298.76
247,248,6,1,5,7396,1.0,34,3008.26
248,249,4,9,3,8028,1.0,58,2540.92
249,250,1,8,7,11507,0.0,72,1525.20

In [21]:
#Data Splitting 
X  = df.drop('Price_USD',axis=1)
y = df['Price_USD']


from mlflow.models import infer_signature

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20, random_state=42)

In [ ]:
#register the signature
signature = infer_signature(X_train,y_train)